feat: qr code scanner with post request
caffeine-addictt/sharkalyze pull request #32
Opened 2024-08-20 08:41 UTC by KenNoYu

# Description
working qr code for frontend and able to send post request and get response from flask api

## Checklist

- [x] Tests passing
- [x] Linting passing
- [x] Changes works (for reviewer)

2024-08-20 08:56 UTC, caffeine-addictt requested changes
No testing done on my side, just some remarks and inconsistencies briefly looking through this

2024-08-20 08:56 UTC, caffeine-addictt commented on client/src/pages/qr/qr.tsx
> +  }, [scannedResult]);
`sendURL` is missing from useEffect dependency array here

2024-08-20 08:56 UTC, caffeine-addictt commented on client/src/pages/qr/route-map.tsx
> +  '/qrReader': {
Do not use camelCase for routes. Use nested routes or default to `-` syntax AKA `/qr-reader`

2024-08-20 08:56 UTC, caffeine-addictt commented on client/src/pages/route-map.tsx
> +import qrRouteMap from './qr/route-map';
Follow convention `@pages/qr/route-map`

2024-08-20 08:56 UTC, caffeine-addictt commented on client/src/styles/qr.css
Don't use css files in tailwind projects

2024-08-20 08:56 UTC, caffeine-addictt commented on server/src/routes/api.py
> +@app.route(f"{BASE_URL}/qr_analyse", methods=["POST"])
Do not use `_` for routes. Use either nested `a/b` or hyphens `a-b`

2024-08-27 04:48 UTC, caffeine-addictt requested changes
No testing done on my side, just skimming through the code

2024-08-27 04:48 UTC, caffeine-addictt commented on client/package.json
> +    "flask-cors": "^0.0.1",
Why did you add flask-cors to client?

2024-08-27 04:48 UTC, caffeine-addictt commented on server/src/routes/api.py
> +    if request.method == "POST":
`@app.route(f"{BASE_URL}/qr-analyse", methods=["POST"])` already makes it so that this function will only trigger if it is a POST request. the check for POST request on line 15 is unnecessary

2024-08-27 05:21 UTC, KenNoYu commented on client/package.json
> +    "flask-cors": "^0.0.1",
i think the error was from the client side

2024-08-27 06:55 UTC, caffeine-addictt submitted a review, later dismissed
No testing done on my side, but code quality wise LGTM

2024-08-27 10:04 UTC, AndrewAce submitted a review, later dismissed
Thank you Jian Yu! Good work! Proud of you.

2024-08-27 13:38 UTC, caffeine-addictt commented
@AndrewAce did you test if the changes work?

2024-08-27 15:31 UTC, KenNoYu commented
code tested and works by ji wei

2024-08-27 15:46 UTC, caffeine-addictt approved these changes
lgtm

2024-08-27 16:04 UTC, Jiwei1212 approved these changes

2024-08-27 16:04 UTC, merged

2024-08-27 16:10 UTC, caffeine-addictt commented
@Jiwei1212 you didnt change the merge message to conform to CONTRIBUTING.md?